"""Against real fixtures, not synthetic one-liners (SPEC.md §11):
`fixtures/requirements.txt` is a real `pip-compile requirements.in`
output (flask==3.0.3 pinned), `fixtures/poetry.lock` a real
`poetry lock` output (requests==2.31.0 pinned) — both generated by
actually running the real tools, not hand-typed."""

from __future__ import annotations

from pathlib import Path

from app.resolve.lockfile import find_lockfile, parse_lockfile, parse_poetry_lock, parse_requirements_txt

FIXTURES = Path(__file__).parent / "fixtures"


def test_parse_real_pip_compile_output():
    pinned = parse_requirements_txt(FIXTURES / "requirements.txt")
    assert pinned["flask"] == "3.0.3"
    assert pinned["jinja2"] == "3.1.6"
    # markupsafe's real `# via` comment in this fixture spans two lines
    # ("# via\n#   jinja2\n#   werkzeug") — confirms the comment-stripper
    # doesn't choke on a multi-line via block.
    assert pinned["markupsafe"] == "3.0.3"
    assert "werkzeug" in pinned


def test_parse_real_poetry_lock():
    pinned = parse_poetry_lock(FIXTURES / "poetry.lock")
    assert pinned["requests"] == "2.31.0"
    assert "urllib3" in pinned
    assert "certifi" in pinned


def test_find_lockfile_prefers_pip_compile(tmp_path):
    (tmp_path / "requirements.txt").write_text("flask==3.0.3\n")
    (tmp_path / "poetry.lock").write_text("[[package]]\nname='x'\nversion='1'\n")
    kind, path = find_lockfile(tmp_path)
    assert kind == "pip-compile"
    assert path.name == "requirements.txt"


def test_find_lockfile_none(tmp_path):
    assert find_lockfile(tmp_path) is None


def test_parse_lockfile_dispatches_by_kind():
    kind, path = find_lockfile(FIXTURES)
    assert kind == "pip-compile"
    assert parse_lockfile(kind, path) == parse_requirements_txt(path)


def test_normalization_folds_underscores_and_case(tmp_path):
    req = tmp_path / "requirements.txt"
    req.write_text("Some_Package==1.2.3\n    # via -r requirements.in\n")
    pinned = parse_requirements_txt(req)
    assert pinned == {"some-package": "1.2.3"}
