"""add node.drift_detail

Revision ID: 079ecd0e96f2
Revises: ddb1cfe69d33
Create Date: 2026-09-10 19:23:12.102348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079ecd0e96f2'
down_revision: Union[str, Sequence[str], None] = 'ddb1cfe69d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('drift_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'drift_detail')
    # ### end Alembic commands ###
