"""initial scan/node/edge tables

Revision ID: ddb1cfe69d33
Revises: 
Create Date: 2026-09-10 18:50:11.671056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb1cfe69d33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('lockfile_kind', sa.String(), nullable=True),
    sa.Column('depth_cap', sa.Integer(), nullable=False),
    sa.Column('total_package_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('package_version', sa.String(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('vuln_severity', sa.String(), nullable=False),
    sa.Column('vuln_detail', sa.Text(), nullable=True),
    sa.Column('drift_status', sa.String(), nullable=False),
    sa.Column('providence_status', sa.String(), nullable=False),
    sa.Column('policy_status', sa.String(), nullable=False),
    sa.Column('repo_stars', sa.Integer(), nullable=True),
    sa.Column('repo_last_commit', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'package_name', name='uq_node_scan_package')
    )
    op.create_table('edge',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('from_node', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('to_node', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['from_node'], ['node.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.ForeignKeyConstraint(['to_node'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge')
    op.drop_table('node')
    op.drop_table('scan')
    # ### end Alembic commands ###
